#############################################################################
# Makefile for building: build/Minesweeper.app/Contents/MacOS/Minesweeper
# Generated by qmake (3.1) (Qt 5.9.1)
# Project:  Minesweeper.pro
# Template: app
# Command: /usr/local/Cellar/qt/5.9.1/bin/qmake -o Makefile Minesweeper.pro -spec macx-clang CONFIG+=x86_64
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers -Ibuild/moc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/usr/local/Cellar/qt/5.9.1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.9.1/lib
QMAKE         = /usr/local/Cellar/qt/5.9.1/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/Cellar/qt/5.9.1/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/Cellar/qt/5.9.1/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Minesweeper1.0.0
DISTDIR = /Users/thomasbertels/dev/qt/projects/UI-Design/U4/Minesweeper/Minesweeper/build/objects/Minesweeper1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/5.9.1/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/objects/

####### Files

SOURCES       = main.cpp \
		minesweeper.cpp \
		helpdialog.cpp \
		statistikdialog.cpp \
		settingsdialog.cpp \
		gamemode.cpp \
		statistics.cpp \
		services.cpp qrc_res.cpp \
		build/moc/moc_minesweeper.cpp \
		build/moc/moc_helpdialog.cpp \
		build/moc/moc_statistikdialog.cpp \
		build/moc/moc_settingsdialog.cpp
OBJECTS       = build/objects/main.o \
		build/objects/minesweeper.o \
		build/objects/helpdialog.o \
		build/objects/statistikdialog.o \
		build/objects/settingsdialog.o \
		build/objects/gamemode.o \
		build/objects/statistics.o \
		build/objects/services.o \
		build/objects/qrc_res.o \
		build/objects/moc_minesweeper.o \
		build/objects/moc_helpdialog.o \
		build/objects/moc_statistikdialog.o \
		build/objects/moc_settingsdialog.o
DIST          = /usr/local/Cellar/qt/5.9.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/lex.prf \
		Minesweeper.pro minesweeper.h \
		helpdialog.h \
		statistikdialog.h \
		settingsdialog.h \
		gamemode.h \
		statistics.h \
		services.h main.cpp \
		minesweeper.cpp \
		helpdialog.cpp \
		statistikdialog.cpp \
		settingsdialog.cpp \
		gamemode.cpp \
		statistics.cpp \
		services.cpp
QMAKE_TARGET  = Minesweeper
DESTDIR       = build/
TARGET        = build/Minesweeper.app/Contents/MacOS/Minesweeper

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_minesweeper.h ui_helpdialog.h ui_statistikdialog.h ui_settingsdialog.h $(OBJECTS)  
	@test -d build/Minesweeper.app/Contents/MacOS/ || mkdir -p build/Minesweeper.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Minesweeper.pro /usr/local/Cellar/qt/5.9.1/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.9.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.9.1/mkspecs/features/lex.prf \
		Minesweeper.pro \
		res.qrc \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/QtWidgets.prl \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Minesweeper.pro -spec macx-clang CONFIG+=x86_64
/usr/local/Cellar/qt/5.9.1/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.9.1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.9.1/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.9.1/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.9.1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.9.1/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.9.1/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.9.1/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.9.1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_cgl_support_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.9.1/mkspecs/features/lex.prf:
Minesweeper.pro:
res.qrc:
/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/QtWidgets.prl:
/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Minesweeper.pro -spec macx-clang CONFIG+=x86_64

qmake_all: FORCE

build/Minesweeper.app/Contents/PkgInfo: 
	@test -d build/Minesweeper.app/Contents || mkdir -p build/Minesweeper.app/Contents
	@$(DEL_FILE) build/Minesweeper.app/Contents/PkgInfo
	@echo "APPL????" > build/Minesweeper.app/Contents/PkgInfo
build/Minesweeper.app/Contents/Resources/empty.lproj: 
	@test -d build/Minesweeper.app/Contents/Resources || mkdir -p build/Minesweeper.app/Contents/Resources
	@touch build/Minesweeper.app/Contents/Resources/empty.lproj
	
build/Minesweeper.app/Contents/Info.plist: 
	@test -d build/Minesweeper.app/Contents || mkdir -p build/Minesweeper.app/Contents
	@$(DEL_FILE) build/Minesweeper.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Minesweeper,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Minesweeper,g" -e "s,@LIBRARY@,Minesweeper,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/5.9.1/mkspecs/macx-clang/Info.plist.app >build/Minesweeper.app/Contents/Info.plist

all: Makefile \
		build/Minesweeper.app/Contents/PkgInfo \
		build/Minesweeper.app/Contents/Resources/empty.lproj \
		build/Minesweeper.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/5.9.1/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents minesweeper.h helpdialog.h statistikdialog.h settingsdialog.h gamemode.h statistics.h services.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp minesweeper.cpp helpdialog.cpp statistikdialog.cpp settingsdialog.cpp gamemode.cpp statistics.cpp services.cpp $(DISTDIR)/
	$(COPY_FILE) --parents minesweeper.ui helpdialog.ui statistikdialog.ui settingsdialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r build/Minesweeper.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		/usr/local/Cellar/qt/5.9.1/bin/rcc \
		res/Maus_mittlererklick.png \
		res/Maus_rechtsklick.png \
		res/Mine.png \
		res/Flag.png \
		res/Minefield.jpg \
		res/Maus_linksklick.png
	/usr/local/Cellar/qt/5.9.1/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_moc_predefs_make_all: build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc/moc_predefs.h
build/moc/moc_predefs.h: /usr/local/Cellar/qt/5.9.1/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o build/moc/moc_predefs.h /usr/local/Cellar/qt/5.9.1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc/moc_minesweeper.cpp build/moc/moc_helpdialog.cpp build/moc/moc_statistikdialog.cpp build/moc/moc_settingsdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_minesweeper.cpp build/moc/moc_helpdialog.cpp build/moc/moc_statistikdialog.cpp build/moc/moc_settingsdialog.cpp
build/moc/moc_minesweeper.cpp: /usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QDate \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qdatetime.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/QMouseEvent \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QTableWidget \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QtDebug \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QScrollBar \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qscrollbar.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QDir \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qdir.h \
		statistikdialog.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qdialog.h \
		gamemode.h \
		statistics.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qstring.h \
		services.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/QList \
		helpdialog.h \
		settingsdialog.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		minesweeper.h \
		build/moc/moc_predefs.h \
		/usr/local/Cellar/qt/5.9.1/bin/moc
	/usr/local/Cellar/qt/5.9.1/bin/moc $(DEFINES) --include ./build/moc//moc_predefs.h -I/usr/local/Cellar/qt/5.9.1/mkspecs/macx-clang -I/Users/thomasbertels/dev/qt/projects/UI-Design/U4/Minesweeper/Minesweeper -I/Users/thomasbertels/dev/qt/projects/UI-Design/U4/Minesweeper/Minesweeper -I/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/usr/local/Cellar/qt/5.9.1/lib minesweeper.h -o build/moc/moc_minesweeper.cpp

build/moc/moc_helpdialog.cpp: /usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qdialog.h \
		helpdialog.h \
		build/moc/moc_predefs.h \
		/usr/local/Cellar/qt/5.9.1/bin/moc
	/usr/local/Cellar/qt/5.9.1/bin/moc $(DEFINES) --include ./build/moc//moc_predefs.h -I/usr/local/Cellar/qt/5.9.1/mkspecs/macx-clang -I/Users/thomasbertels/dev/qt/projects/UI-Design/U4/Minesweeper/Minesweeper -I/Users/thomasbertels/dev/qt/projects/UI-Design/U4/Minesweeper/Minesweeper -I/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/usr/local/Cellar/qt/5.9.1/lib helpdialog.h -o build/moc/moc_helpdialog.cpp

build/moc/moc_statistikdialog.cpp: /usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QtDebug \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qdebug.h \
		gamemode.h \
		statistics.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qstring.h \
		services.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/qevent.h \
		statistikdialog.h \
		build/moc/moc_predefs.h \
		/usr/local/Cellar/qt/5.9.1/bin/moc
	/usr/local/Cellar/qt/5.9.1/bin/moc $(DEFINES) --include ./build/moc//moc_predefs.h -I/usr/local/Cellar/qt/5.9.1/mkspecs/macx-clang -I/Users/thomasbertels/dev/qt/projects/UI-Design/U4/Minesweeper/Minesweeper -I/Users/thomasbertels/dev/qt/projects/UI-Design/U4/Minesweeper/Minesweeper -I/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/usr/local/Cellar/qt/5.9.1/lib statistikdialog.h -o build/moc/moc_statistikdialog.cpp

build/moc/moc_settingsdialog.cpp: /usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QtDebug \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		statistics.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qstring.h \
		gamemode.h \
		services.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/qevent.h \
		settingsdialog.h \
		build/moc/moc_predefs.h \
		/usr/local/Cellar/qt/5.9.1/bin/moc
	/usr/local/Cellar/qt/5.9.1/bin/moc $(DEFINES) --include ./build/moc//moc_predefs.h -I/usr/local/Cellar/qt/5.9.1/mkspecs/macx-clang -I/Users/thomasbertels/dev/qt/projects/UI-Design/U4/Minesweeper/Minesweeper -I/Users/thomasbertels/dev/qt/projects/UI-Design/U4/Minesweeper/Minesweeper -I/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/usr/local/Cellar/qt/5.9.1/lib settingsdialog.h -o build/moc/moc_settingsdialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_minesweeper.h ui_helpdialog.h ui_statistikdialog.h ui_settingsdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_minesweeper.h ui_helpdialog.h ui_statistikdialog.h ui_settingsdialog.h
ui_minesweeper.h: minesweeper.ui \
		/usr/local/Cellar/qt/5.9.1/bin/uic
	/usr/local/Cellar/qt/5.9.1/bin/uic minesweeper.ui -o ui_minesweeper.h

ui_helpdialog.h: helpdialog.ui \
		/usr/local/Cellar/qt/5.9.1/bin/uic
	/usr/local/Cellar/qt/5.9.1/bin/uic helpdialog.ui -o ui_helpdialog.h

ui_statistikdialog.h: statistikdialog.ui \
		/usr/local/Cellar/qt/5.9.1/bin/uic
	/usr/local/Cellar/qt/5.9.1/bin/uic statistikdialog.ui -o ui_statistikdialog.h

ui_settingsdialog.h: settingsdialog.ui \
		/usr/local/Cellar/qt/5.9.1/bin/uic
	/usr/local/Cellar/qt/5.9.1/bin/uic settingsdialog.ui -o ui_settingsdialog.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/objects/main.o: main.cpp minesweeper.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QDate \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qdatetime.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/QMouseEvent \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QTableWidget \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QtDebug \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QScrollBar \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qscrollbar.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QDir \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qdir.h \
		statistikdialog.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qdialog.h \
		gamemode.h \
		statistics.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qstring.h \
		services.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/QList \
		helpdialog.h \
		settingsdialog.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/main.o main.cpp

build/objects/minesweeper.o: minesweeper.cpp minesweeper.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QDate \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qdatetime.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/QMouseEvent \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QTableWidget \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QtDebug \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QScrollBar \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qscrollbar.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QDir \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qdir.h \
		statistikdialog.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qdialog.h \
		gamemode.h \
		statistics.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qstring.h \
		services.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/QList \
		helpdialog.h \
		settingsdialog.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		ui_minesweeper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/minesweeper.o minesweeper.cpp

build/objects/helpdialog.o: helpdialog.cpp helpdialog.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_helpdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/helpdialog.o helpdialog.cpp

build/objects/statistikdialog.o: statistikdialog.cpp statistikdialog.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QtDebug \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qdebug.h \
		gamemode.h \
		statistics.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qstring.h \
		services.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/qevent.h \
		ui_statistikdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/statistikdialog.o statistikdialog.cpp

build/objects/settingsdialog.o: settingsdialog.cpp settingsdialog.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QtDebug \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		statistics.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qstring.h \
		gamemode.h \
		services.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/qevent.h \
		ui_settingsdialog.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/Cellar/qt/5.9.1/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/settingsdialog.o settingsdialog.cpp

build/objects/gamemode.o: gamemode.cpp gamemode.h \
		statistics.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/gamemode.o gamemode.cpp

build/objects/statistics.o: statistics.cpp statistics.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/statistics.o statistics.cpp

build/objects/services.o: services.cpp services.h \
		gamemode.h \
		statistics.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.1/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/services.o services.cpp

build/objects/qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/qrc_res.o qrc_res.cpp

build/objects/moc_minesweeper.o: build/moc/moc_minesweeper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/moc_minesweeper.o build/moc/moc_minesweeper.cpp

build/objects/moc_helpdialog.o: build/moc/moc_helpdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/moc_helpdialog.o build/moc/moc_helpdialog.cpp

build/objects/moc_statistikdialog.o: build/moc/moc_statistikdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/moc_statistikdialog.o build/moc/moc_statistikdialog.cpp

build/objects/moc_settingsdialog.o: build/moc/moc_settingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/moc_settingsdialog.o build/moc/moc_settingsdialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

